/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PEO45cFOgKr
 */
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { XIcon } from './ui/icons/XIcon'

export function FoodModal() {
  return (
    <div
      key="1"
      className="fixed inset-0 flex items-center justify-center bg-gray-500 bg-opacity-75 p-4">
      <div className="w-full max-w-sm rounded-lg bg-white">
        <div className="p-6">
          <div className="flex items-center justify-between pb-4">
            <div className="space-y-1">
              <h3 className="text-lg font-semibold leading-6 tracking-tighter text-gray-900">
                Add new food item
              </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Enter the details of the food item below.
              </p>
            </div>
            <button className="text-gray-400 hover:text-gray-500">
              <XIcon className="h-6 w-6" />
            </button>
          </div>
          <form>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700" htmlFor="food-name">
                  Food Name
                </label>
                <Input
                  className="ring-1 ring-gray-200 ring-opacity-70 focus:ring-2 focus:ring-gray-300"
                  id="food-name"
                  placeholder="E.g. Spaghetti"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700" htmlFor="food-calories">
                  Calories
                </label>
                <Input
                  className="ring-1 ring-gray-200 ring-opacity-70 focus:ring-2 focus:ring-gray-300"
                  id="food-calories"
                  placeholder="E.g. 250"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700" htmlFor="food-serving">
                  Serving Size
                </label>
                <Input
                  className="ring-1 ring-gray-200 ring-opacity-70 focus:ring-2 focus:ring-gray-300"
                  id="food-serving"
                  placeholder="E.g. 1 cup"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700" htmlFor="food-protein">
                  Protein
                </label>
                <Input
                  className="ring-1 ring-gray-200 ring-opacity-70 focus:ring-2 focus:ring-gray-300"
                  id="food-protein"
                  placeholder="E.g. 10g"
                />
              </div>
            </div>
            <div className="mt-6 flex justify-end">
              <Button className="mr-2" variant="outline">
                Cancel
              </Button>
              <Button>Add Item</Button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}
// const data = [
//   {
//     average: 4,
//     date: '04/01/24'
//   },
//   {
//     average: 7,
//     date: '06/01/24'
//   },
//   {
//     average: 6,
//     date: '08/01/24'
//   },
//   {
//     average: 4,
//     date: '12/01/24'
//   },
//   {
//     average: 7,
//     date: '14/01/24'
//   },
//   {
//     average: 6,
//     date: '21/01/24'
//   },
//   {
//     average: 6,
//     date: '27/01/24'
//   },
//   {
//     average: 6,
//     date: '04/02/24'
//   },
//   {
//     average: 6,
//     date: '06/02/24'
//   },
//   {
//     average: 6,
//     date: '08/02/24'
//   }
// ]